import type { SupabaseClient } from '@supabase/supabase-js';
import type { Cache, Profile } from '@/types/ezr';
export const EMPTY_CACHE:Cache={customers:[],sellers:[],banks:[],settings:{},stock:[],newStock:[],purchases:[],sales:[],expenses:[],ledger:[],accessoryTypes:[],callLodges:[],whatsappDeliveries:[]};
export async function getProfile(sb:SupabaseClient,userId:string):Promise<Profile>{const {data,error}=await sb.from('profiles').select('*').eq('id',userId).single();if(error||!data)throw new Error('This login has no profile set up yet. Ask your Admin to add you in the profiles table.');return{id:data.id,fullName:data.full_name,role:data.role};}
export async function genId(sb:SupabaseClient,seqName:string,prefix:string,padLen=4){const{data,error}=await sb.rpc('generate_id',{seq_name:seqName,prefix,pad_len:padLen});if(error)throw error;return String(data)}
export async function fetchAll(sb:SupabaseClient):Promise<Cache>{
 const [customers,sellers,banks,settings,stock,mods,newStock,newSerials,purchases,sales,expenses,ledger,accTypes,callLodges,whatsappDeliveries]=await Promise.all([
  sb.from('customers').select('*').order('name'),sb.from('sellers').select('*').order('name'),sb.from('banks').select('*'),sb.from('settings').select('*'),sb.from('stock').select('*').order('id',{ascending:false}),sb.from('stock_modifications').select('*'),sb.from('new_stock_products').select('*').order('created_at',{ascending:false}),sb.from('new_stock_serials').select('*'),sb.from('purchases').select('*').order('date',{ascending:false}),sb.from('sales').select('*').order('date',{ascending:false}),sb.from('expenses').select('*').order('date',{ascending:false}),sb.from('ledger').select('*').order('date',{ascending:false}),sb.from('accessory_types').select('*').order('name'),sb.from('call_lodges').select('*').order('date',{ascending:false}),sb.from('invoice_whatsapp_deliveries').select('*').order('created_at',{ascending:false})]);
 const err=[customers,sellers,banks,settings,stock,mods,newStock,newSerials,purchases,sales,expenses,ledger,accTypes,callLodges,whatsappDeliveries].find(x=>x.error)?.error;if(err)throw err;
 const modsList=mods.data||[], serialList=newSerials.data||[];return{
 customers:(customers.data||[]),sellers:(sellers.data||[]),banks:(banks.data||[]).map(b=>({id:b.id,name:b.name,accountNumber:b.account_number,openingBalance:Number(b.opening_balance||0)})),settings:Object.fromEntries((settings.data||[]).map(s=>[s.key,s.value])),
 stock:(stock.data||[]).map(s=>({id:s.id,category:s.category,condition:s.condition,status:s.status,model:s.model,processor:s.processor,motherboard:s.motherboard,ram:s.ram,gpu:s.gpu,ssd:s.ssd,hdd:s.hdd,display:s.display,serial:s.serial,accessoryType:s.accessory_type,brand:s.brand,description:s.description,purchasePrice:Number(s.purchase_price||0),purchaseDate:s.purchase_date,sellerId:s.seller_id,sellerName:s.seller_name,notes:s.notes,createdByName:s.created_by_name,blockedFor:s.blocked_for||null,modifications:modsList.filter(m=>m.stock_id===s.id).map(m=>({description:m.description,cost:Number(m.cost||0),date:m.date,mode:m.mode,bankId:m.bank_id,createdByName:m.created_by_name,type:m.type||'Added',fieldKey:m.field_key||null}))})),
 newStock:(newStock.data||[]).map(p=>({id:p.id,serialRequired:Boolean(p.serial_required),accessoryType:p.accessory_type,brand:p.brand,modelNo:p.model_no,quantity:Number(p.quantity||0),initialQuantity:Number(p.initial_quantity||0),purchasePrice:Number(p.purchase_price||0),purchaseDate:p.purchase_date,sellerId:p.seller_id,sellerName:p.seller_name,paymentMode:p.payment_mode,bankId:p.bank_id,createdByName:p.created_by_name,serials:serialList.filter(s=>s.product_id===p.id).map(s=>({id:s.id,productId:s.product_id,serialNumber:s.serial_number,sold:Boolean(s.sold),saleId:s.sale_id||null}))})),
 purchases:(purchases.data||[]).map(p=>({id:p.id,stockId:p.stock_id,newProductId:p.new_product_id||null,sellerId:p.seller_id,sellerName:p.seller_name,productLabel:p.product_label,purchasePrice:Number(p.purchase_price||0),qty:Number(p.qty||1),date:p.date,paymentMode:p.payment_mode,bankId:p.bank_id,amountPaid:Number(p.amount_paid||0),due:Number(p.due||0),createdByName:p.created_by_name})),
 sales:(sales.data||[]).map(s=>({id:s.id,billNo:s.bill_no,stockId:s.stock_id,stockLabel:s.stock_label,buyerId:s.buyer_id,buyerName:s.buyer_name,salePrice:Number(s.sale_price||0),date:s.date,paymentMode:s.payment_mode,bankId:s.bank_id,amountReceived:Number(s.amount_received||0),due:Number(s.due||0),createdByName:s.created_by_name,serviceCharge:Number(s.service_charge||0),lineItems:Array.isArray(s.line_items)?s.line_items.map((l:any)=>({newProductId:l.new_product_id,stockLabel:l.stock_label,quantity:Number(l.quantity),unitPrice:Number(l.unit_price),purchasePrice:Number(l.purchase_price),serialNumbers:Array.isArray(l.serial_numbers)?l.serial_numbers:[]})):[],stockSource:(s.stock_source||'legacy') as 'legacy'|'new',newProductId:s.new_product_id||null,quantity:Number(s.quantity||1),unitPrice:Number(s.unit_price??s.sale_price??0),serialNumbers:Array.isArray(s.serial_numbers)?s.serial_numbers:[]})),
 expenses:(expenses.data||[]).map(e=>({id:e.id,category:e.category,amount:Number(e.amount||0),paymentMode:e.payment_mode,bankId:e.bank_id,date:e.date,note:e.note,createdByName:e.created_by_name})),
 ledger:(ledger.data||[]).map(l=>({id:l.id,date:l.date,type:l.type,mode:l.mode,bankId:l.bank_id,amount:Number(l.amount||0),refType:l.ref_type,refId:l.ref_id,note:l.note,createdByName:l.created_by_name})),
 accessoryTypes:(accTypes.data||[]).map(t=>t.name),callLodges:(callLodges.data||[]).map(c=>({id:c.id,date:c.date,category:c.category,customerId:c.customer_id,customerName:c.customer_name,customerPhone:c.customer_phone,customerAddress:c.customer_address,description:c.description,status:c.status,serviceNote:c.service_note,createdByName:c.created_by_name})),whatsappDeliveries:(whatsappDeliveries.data||[]).map(w=>({id:Number(w.id),saleId:w.sale_id,customerId:w.customer_id,phone:w.phone,status:w.status,messageId:w.whatsapp_message_id,mediaId:w.whatsapp_media_id,errorMessage:w.error_message,sentAt:w.sent_at,createdByName:w.created_by_name,createdAt:w.created_at}))};
}
export async function insertLedger(sb:SupabaseClient,profile:Profile,input:{date:string;type:string;mode:string;bankId?:string|null;amount:number;refType?:string;refId?:string;note?:string}){const{error}=await sb.from('ledger').insert({date:input.date,type:input.type,mode:input.mode,bank_id:input.bankId||null,amount:input.amount,ref_type:input.refType||null,ref_id:input.refId||null,note:input.note||'',created_by:profile.id,created_by_name:profile.fullName});if(error)throw error;}

export async function replaceLedger(sb:SupabaseClient,profile:Profile,refType:string,refId:string,input:{date:string;type:string;mode:string;bankId?:string|null;amount:number;note?:string}|null){
 const {error}=await sb.rpc('replace_reference_ledger',{p_ref_type:refType,p_ref_id:refId,p_entry:input?{date:input.date,type:input.type,mode:input.mode,bank_id:input.bankId||null,amount:input.amount,ref_type:refType,ref_id:refId,note:input.note||'',created_by:profile.id,created_by_name:profile.fullName}:null});
 if(error)throw Error(error.code==='PGRST202'?'Apply the balance-protection database migration before editing payments.':error.message);
}
