'use client';
import {createContext,useContext,useRef,useState} from 'react';
import type {Customer} from '@/types/ezr';
import {SearchPicker} from './SearchPicker';
export type ContactDraft={name:string;phone:string;address:string};
export const ContactContext=createContext<{customers:Customer[];sellers:Customer[];create:(kind:'customer'|'seller',draft:ContactDraft)=>Promise<Customer>}|null>(null);
export function ContactPicker({kind,name,label,contacts=[],initial=''}:{kind:'customer'|'seller';name:string;label:string;contacts?:Customer[];initial?:string}){
 const context=useContext(ContactContext),[selected,setSelected]=useState(initial),[added,setAdded]=useState<Customer[]>([]),[creating,setCreating]=useState(false),[draft,setDraft]=useState<ContactDraft>({name:'',phone:'',address:''}),[error,setError]=useState(''),[saving,setSaving]=useState(false);const pending=useRef(false);
 const rows=[...new Map([...(context?(kind==='customer'?context.customers:context.sellers):contacts),...added].map(c=>[c.id,c])).values()];
 async function save(){if(pending.current||!context)return;const clean={name:draft.name.trim(),phone:draft.phone.trim(),address:draft.address.trim()};if(!clean.name||!clean.phone||!clean.address){setError('Name, phone number and location are required.');return}pending.current=true;setSaving(true);setError('');try{const contact=await context.create(kind,clean);setAdded(a=>[...a,contact]);setSelected(contact.id);setCreating(false);setDraft({name:'',phone:'',address:''})}catch(e){setError(e instanceof Error?e.message:'Could not save contact. Please try again.')}finally{pending.current=false;setSaving(false)}}
 return <div className="contactPicker">{creating?<div className="contactDraft" onKeyDown={e=>{if(e.key==='Enter'&&e.target instanceof HTMLInputElement){e.preventDefault();void save()}}}><b>Add {label.toLowerCase()}</b><input type="hidden" name={name} value=""/><fieldset className="saleFields" disabled={saving}>{(['name','phone','address'] as const).map(k=><div className="field" key={k}><label htmlFor={`${name}-new-${k}`}>{k==='address'?'Location / Address':k==='phone'?'Phone number':'Name'}</label><input id={`${name}-new-${k}`} type={k==='phone'?'tel':'text'} value={draft[k]} required onChange={e=>setDraft(d=>({...d,[k]:e.target.value}))}/></div>)}</fieldset><div className="actions"><button type="button" className="button" disabled={saving} onClick={()=>void save()}>{saving?'Saving…':`Save ${label.toLowerCase()}`}</button><button type="button" className="button secondary" disabled={saving} onClick={()=>{setCreating(false);setError('')}}>Cancel</button></div><small>The contact is saved to your contacts list and selected for this entry.</small></div>:<><SearchPicker label={label} name={name} required value={selected} onChange={setSelected} options={rows.map(c=>({id:c.id,label:c.name,detail:[c.phone,c.address].filter(Boolean).join(' · '),search:c.id}))}/>{context&&<button type="button" className="button secondary small contactAdd" onClick={()=>{setCreating(true);setError('')}}>+ Add new {label.toLowerCase()}</button>}</>}{error&&<p className="error" role="alert">{error}</p>}</div>;
}
