'use client';
import {useMemo,useState} from 'react';
import {fmtDate,inr} from '@/lib/ezr-utils';
import type {Customer,Ledger,OpeningDue,Purchase,Sale} from '@/types/ezr';

type PartyKind='customer'|'seller';
export type PartyGroup={key:string;id?:string;name:string;phone?:string;address?:string;due:number;transactions:number;lastDate:string;sales:Sale[];purchases:Purchase[];openingDues:OpeningDue[]};
const keyOf=(id:string|undefined,name:string|undefined)=>id?`id:${id}`:`name:${String(name||'Unknown').trim().toLowerCase()}`;
const newest=<T extends {date:string;id:string}>(rows:T[])=>[...rows].sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id,undefined,{numeric:true}));
const blank=(key:string,id:string|undefined,name:string,contact?:Customer,date='') :PartyGroup=>({key,id,name:contact?.name||name,phone:contact?.phone,address:contact?.address,due:0,transactions:0,lastDate:date,sales:[],purchases:[],openingDues:[]});
export function groupCustomerDues(sales:Sale[],customers:Customer[],openingDues:OpeningDue[]):PartyGroup[]{const groups=new Map<string,PartyGroup>();for(const sale of newest(sales)){const key=keyOf(sale.buyerId,sale.buyerName),contact=customers.find(c=>c.id===sale.buyerId),group=groups.get(key)||blank(key,sale.buyerId,sale.buyerName||'Unknown buyer',contact,sale.date);group.sales.push(sale);group.due+=Number(sale.due||0);group.transactions++;if(sale.date>group.lastDate)group.lastDate=sale.date;groups.set(key,group)}for(const due of newest(openingDues.filter(d=>d.partyKind==='customer'))){const key=keyOf(due.partyId,due.partyName),contact=customers.find(c=>c.id===due.partyId),group=groups.get(key)||blank(key,due.partyId,due.partyName||'Unknown buyer',contact,due.date);group.openingDues.push(due);group.due+=Math.max(0,due.amount-due.paidAmount);group.transactions++;if(due.date>group.lastDate)group.lastDate=due.date;groups.set(key,group)}return [...groups.values()].sort((a,b)=>b.due-a.due||a.name.localeCompare(b.name));}
export function groupSellerDues(purchases:Purchase[],sellers:Customer[],openingDues:OpeningDue[]):PartyGroup[]{const groups=new Map<string,PartyGroup>();for(const purchase of newest(purchases)){const key=keyOf(purchase.sellerId,purchase.sellerName),contact=sellers.find(c=>c.id===purchase.sellerId),group=groups.get(key)||blank(key,purchase.sellerId,purchase.sellerName||'Unknown seller',contact,purchase.date);group.purchases.push(purchase);group.due+=Number(purchase.due||0);group.transactions++;if(purchase.date>group.lastDate)group.lastDate=purchase.date;groups.set(key,group)}for(const due of newest(openingDues.filter(d=>d.partyKind==='seller'))){const key=keyOf(due.partyId,due.partyName),contact=sellers.find(c=>c.id===due.partyId),group=groups.get(key)||blank(key,due.partyId,due.partyName||'Unknown seller',contact,due.date);group.openingDues.push(due);group.due+=Math.max(0,due.amount-due.paidAmount);group.transactions++;if(due.date>group.lastDate)group.lastDate=due.date;groups.set(key,group)}return [...groups.values()].sort((a,b)=>b.due-a.due||a.name.localeCompare(b.name));}
export function DuesView({sales,purchases,ledger,openingDues,customers,sellers,onReceive,onPay,onAddOpeningDue}:{sales:Sale[];purchases:Purchase[];ledger:Ledger[];openingDues:OpeningDue[];customers:Customer[];sellers:Customer[];onReceive:(person:PartyGroup)=>void;onPay:(person:PartyGroup)=>void;onAddOpeningDue?:()=>void}){
 const[mode,setMode]=useState<PartyKind>('customer'),[selected,setSelected]=useState<string|null>(null);
 const customerGroups=useMemo(()=>groupCustomerDues(sales,customers,openingDues),[sales,customers,openingDues]),sellerGroups=useMemo(()=>groupSellerDues(purchases,sellers,openingDues),[purchases,sellers,openingDues]);
 const all=mode==='customer'?customerGroups:sellerGroups,outstanding=all.filter(p=>p.due>0),person=all.find(p=>p.key===selected);
 const total=outstanding.reduce((sum,p)=>sum+p.due,0);
 const switchMode=(next:PartyKind)=>{setMode(next);setSelected(null)};
 return <><div className="duesToolbar"><div className="tabs"><button className={`tab ${mode==='customer'?'active':''}`} onClick={()=>switchMode('customer')}>Customer Dues ({customerGroups.filter(p=>p.due>0).length})</button><button className={`tab ${mode==='seller'?'active':''}`} onClick={()=>switchMode('seller')}>Seller Dues ({sellerGroups.filter(p=>p.due>0).length})</button></div>{onAddOpeningDue&&<button className="button" onClick={onAddOpeningDue}>+ Add Opening Due</button>}</div>
 {person?<PersonTransactions kind={mode} person={person} ledger={ledger} onBack={()=>setSelected(null)} onAction={mode==='customer'?onReceive:onPay}/>:<><div className="sectionHead"><h3>{mode==='customer'?'Customer':'Seller'} Dues <small>{inr(total)} outstanding</small></h3></div><div className="tableWrap"><table><thead><tr>{['Person','Phone','Location','Transactions','Last Transaction','Total Due','Action'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{outstanding.map(p=><tr key={p.key}><td><b>{p.name}</b>{p.id&&<small className="blockMuted">{p.id}</small>}</td><td>{p.phone||'—'}</td><td>{p.address||'—'}</td><td>{p.transactions}</td><td>{fmtDate(p.lastDate)}</td><td><b className="dueAmount">{inr(p.due)}</b></td><td><button className="button small" onClick={()=>setSelected(p.key)}>View Transactions</button></td></tr>)}</tbody></table>{!outstanding.length&&<div className="empty">No outstanding {mode==='customer'?'customer':'seller'} dues.</div>}</div></>}</>;
}
type StatementRow={key:string;date:string;particulars:string;reference:string;debit:number;credit:number;balance:number};
export function personStatement(kind:PartyKind,person:PartyGroup,ledger:Ledger[]):StatementRow[]{
 const rows:Array<Omit<StatementRow,'balance'>&{order:number}>=[];
 const records=kind==='customer'?person.sales:person.purchases;
 for(const record of records){const total=kind==='customer'?(record as Sale).salePrice:(record as Purchase).purchasePrice*(record as Purchase).qty;rows.push({key:`record-${record.id}`,date:record.date,particulars:kind==='customer'?'Sale invoice':'Stock purchase',reference:record.id,debit:kind==='customer'?total:0,credit:kind==='seller'?total:0,order:0});
  const payments=ledger.filter(l=>l.refId===record.id&&l.refType===(kind==='customer'?'sale':'purchase')&&((kind==='customer'&&l.amount>0)||(kind==='seller'&&l.amount<0)));
  payments.forEach((l,i)=>rows.push({key:`payment-${record.id}-${l.id}-${i}`,date:l.date,particulars:kind==='customer'?'Payment received':'Payment made',reference:record.id,debit:kind==='seller'?Math.abs(l.amount):0,credit:kind==='customer'?Math.abs(l.amount):0,order:1+i/1000}));
 }
 for(const due of person.openingDues)rows.push({key:`opening-${due.id}`,date:due.date,particulars:due.note?`Opening balance · ${due.note}`:'Opening balance',reference:'Carry forward',debit:kind==='customer'?due.amount:0,credit:kind==='seller'?due.amount:0,order:0});
 const accountPayments=ledger.filter(l=>l.refId===person.id&&l.refType===(kind==='customer'?'customer_due':'seller_due'));accountPayments.forEach((l,i)=>rows.push({key:`person-payment-${l.id}-${i}`,date:l.date,particulars:kind==='customer'?'Payment received':'Payment made',reference:'Account payment',debit:kind==='seller'?Math.abs(l.amount):0,credit:kind==='customer'?Math.abs(l.amount):0,order:2+i/1000}));
 const charges=records.reduce((n,r)=>n+(kind==='customer'?(r as Sale).salePrice:(r as Purchase).purchasePrice*(r as Purchase).qty),0)+person.openingDues.reduce((n,d)=>n+d.amount,0),knownPayments=rows.reduce((n,r)=>n+(kind==='customer'?r.credit:r.debit),0),historicalPayment=Math.max(0,Math.round((charges-person.due-knownPayments)*100)/100),dates=[...records.map(r=>r.date),...person.openingDues.map(d=>d.date)];
 if(historicalPayment>0)rows.push({key:'historical-payment',date:dates.sort()[0]||'',particulars:'Recorded payment',reference:'Historical',debit:kind==='seller'?historicalPayment:0,credit:kind==='customer'?historicalPayment:0,order:.5});
 rows.sort((a,b)=>a.date.localeCompare(b.date)||a.order-b.order||a.key.localeCompare(b.key));let balance=0;const calculated=rows.map(row=>{balance+=kind==='customer'?row.debit-row.credit:row.credit-row.debit;return{...row,balance:Math.round(balance*100)/100}});return calculated.reverse();
}
function PersonTransactions({kind,person,ledger,onBack,onAction}:{kind:PartyKind;person:PartyGroup;ledger:Ledger[];onBack:()=>void;onAction:(person:PartyGroup)=>void}){
 const statement=personStatement(kind,person,ledger);
 return <><div className="sectionHead"><h3>{person.name} <small>{person.id||''}</small></h3><button className="button secondary" onClick={onBack}>← Back to people</button></div><div className="personDueSummary"><div className="personDueAction">{person.due>0&&person.id?<button className={`button ${kind==='seller'?'warn':''}`} onClick={()=>onAction(person)}>{kind==='customer'?'Receive Payment':'Pay Seller'}</button>:person.due>0?<small>Payment unavailable: this historical record has no person ID.</small>:<span className="pill green">Fully paid</span>}</div><div><span>Phone</span><b>{person.phone||'—'}</b></div><div><span>Location</span><b>{person.address||'—'}</b></div><div><span>Total Outstanding</span><b className="dueAmount">{inr(person.due)}</b></div></div>
 <div className="tableWrap accountLedger"><table><thead><tr>{['Date','Particulars','Reference','Debit','Credit','Balance'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{statement.map(r=><tr key={r.key}><td>{fmtDate(r.date)}</td><td>{r.particulars}</td><td className="mono">{r.reference}</td><td>{r.debit?inr(r.debit):'—'}</td><td>{r.credit?inr(r.credit):'—'}</td><td><b className={r.balance>0?'dueAmount':''}>{inr(r.balance)}</b></td></tr>)}</tbody></table>{!statement.length&&<div className="empty">No transactions found.</div>}</div><div className="note">{kind==='customer'?'Debit is a sale or opening balance; credit is money received.':'Credit is a purchase or opening balance; debit is money paid.'} Balance is the running amount outstanding.</div></>;
}
