'use client';
import {useRef,useState} from 'react';
import {inr,todayISO} from '@/lib/ezr-utils';
import type {Bank,NewStockProduct,Seller,Sale} from '@/types/ezr';
import {groupProducts,purchaseRange,type ProductGroup} from '@/lib/new-stock-groups';
import {SearchPicker} from './SearchPicker';
import {StockMonthFilter} from './StockMonthFilter';
import {ContactPicker} from './ContactPicker';
export function NewStockForm({accessoryTypes,sellers,banks,existing,onSave}:{accessoryTypes:string[];sellers:Seller[];banks:Bank[];existing:NewStockProduct[];onSave:(fd:FormData)=>Promise<void>}){
 const[paymentMode,setPaymentMode]=useState('Cash'),[type,setType]=useState(''),[brand,setBrand]=useState(''),[model,setModel]=useState(''),[quantity,setQuantity]=useState('1'),[price,setPrice]=useState(''),[serialMode,setSerialMode]=useState(''),[serialText,setSerialText]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);const pending=useRef(false);
 const[paid,setPaid]=useState<string|null>(null);
 const total=Math.round(Number(price||0)*100)*Number(quantity||0)/100,amountPaid=paid??String(total),due=Math.round((total-Number(amountPaid||0))*100)/100;
 const serials=serialText.split(/[\n,]+/).map(s=>s.trim()).filter(Boolean);
 return <form className="newStockEntry" onSubmit={async e=>{e.preventDefault();if(pending.current)return;const fd=new FormData(e.currentTarget);if(!fd.get('accessoryType')||!fd.get('seller')||(paymentMode==='Online'&&!fd.get('bank'))){setError('Select a matching item type, seller and payment account.');return}if(serialMode==='yes'&&(serials.length!==Number(quantity)||new Set(serials.map(s=>s.toLowerCase())).size!==serials.length)){setError('Enter one unique serial number for every unit.');return}setError('');pending.current=true;setSaving(true);try{await onSave(fd)}finally{pending.current=false;setSaving(false)}}}>
 <fieldset className="saleFields" disabled={saving}>
 <div className="entryIntro"><b>Receive new stock</b><span>Find a previous item to fill its details, or enter a new item below.</span></div>
 <SearchPicker label="Previous item (optional)" options={existing.map(p=>({id:p.id,label:`${p.accessoryType} · ${p.brand} ${p.modelNo}`,detail:`${p.id} · Purchase ${inr(p.purchasePrice)}`}))} onChange={id=>{const p=existing.find(x=>x.id===id);if(p){setType(p.accessoryType);setBrand(p.brand);setModel(p.modelNo);setSerialMode(p.serialRequired?'yes':'');setSerialText('')}}}/>
 <div className="grid2 entryBlock">
 <SearchPicker label="Item type" name="accessoryType" required value={type} onChange={setType} options={accessoryTypes.map(x=>({id:x,label:x}))}/>
 <div className="field"><label htmlFor="new-brand">Brand</label><input id="new-brand" name="brand" value={brand} onChange={e=>setBrand(e.target.value)} list="stock-brands" required autoComplete="off"/><datalist id="stock-brands">{[...new Set(existing.map(p=>p.brand))].map(x=><option key={x} value={x}/>)}</datalist></div>
 <div className="field"><label htmlFor="new-model">Model No.</label><input id="new-model" name="modelNo" value={model} onChange={e=>setModel(e.target.value)} list="stock-models" required autoComplete="off"/><datalist id="stock-models">{[...new Set(existing.filter(p=>!brand||p.brand===brand).map(p=>p.modelNo))].map(x=><option key={x} value={x}/>)}</datalist></div>
 <div className="field"><label htmlFor="new-quantity">Quantity</label><input id="new-quantity" name="quantity" type="number" min="1" step="1" required value={quantity} onChange={e=>setQuantity(e.target.value)}/></div>
 <div className="field"><label htmlFor="new-price">Purchase Price / Unit (₹)</label><input id="new-price" name="price" type="number" min="0" step="0.01" required value={price} onChange={e=>setPrice(e.target.value)}/></div>
 <div className="field"><label htmlFor="new-date">Purchase Date</label><input id="new-date" name="date" type="date" max={todayISO()} defaultValue={todayISO()} required/></div>
 </div>
 <div className="serialEntry"><b>Does this item have serial numbers?</b><div className="choiceRow">{[['yes','Yes — enter every serial'],['no','No serial numbers']].map(([v,l])=><label key={v}><input type="radio" name="serialRequired" value={v} required checked={serialMode===v} onChange={()=>{setSerialMode(v);setSerialText('')}}/>{l}</label>)}</div>
 {serialMode==='yes'&&<div className="field"><label htmlFor="new-serials">Serial numbers · {serials.length} / {quantity||0} entered</label><textarea id="new-serials" name="serials" required rows={4} value={serialText} onChange={e=>setSerialText(e.target.value)} placeholder="Scan or enter one serial per line. Commas also separate serials."/><small>Every unit needs its own unique serial number.</small></div>}</div>
 <div className="grid2 entryBlock"><ContactPicker kind="seller" name="seller" label="Seller" contacts={sellers}/><div className="field"><label>Payment Mode</label><div className="choiceRow">{['Cash','Online'].map(m=><label key={m}><input type="radio" name="mode" value={m} checked={paymentMode===m} onChange={()=>setPaymentMode(m)}/>{m}</label>)}</div></div>{paymentMode==='Online'&&<SearchPicker name="bank" label="Bank account" required options={banks.map(b=>({id:b.id,label:b.name}))}/>}</div>
 <div className="grid2 entryBlock"><div className="field"><label htmlFor="purchase-paid">Amount Paid (₹)</label><input id="purchase-paid" name="paid" type="number" min="0" max={Number.isFinite(total)?total:0} step="0.01" required value={amountPaid} onChange={e=>setPaid(e.target.value)}/><small>Enter 0 for a fully unpaid purchase.</small></div><div className="saleSummary"><div>Purchase total: <b>{inr(total)}</b></div><div>Seller due: <b>{inr(Math.max(0,due))}</b></div><small>The unpaid balance is added to Seller Dues automatically.</small></div></div>
 {error&&<p className="error" role="alert">{error}</p>}
 </fieldset><div className="modalActions"><button className="button" disabled={saving}>{saving?'Saving…':'Add New Stock'}</button></div></form>;
}
export type NewStockTree={type:string;quantity:number;brands:Array<{brand:string;quantity:number;models:Array<{model:string;quantity:number;batches:NewStockProduct[]}>}>};
export function groupNewStock(products:NewStockProduct[]):NewStockTree[]{
 const types=new Map<string,{label:string;rows:NewStockProduct[]}>();for(const product of products){const key=product.accessoryType.trim().toLowerCase(),group=types.get(key)||{label:product.accessoryType,rows:[]};group.rows.push(product);types.set(key,group)}
 return [...types.values()].sort((a,b)=>a.label.localeCompare(b.label)).map(type=>{const brands=new Map<string,{label:string;rows:NewStockProduct[]}>();for(const product of type.rows){const key=product.brand.trim().toLowerCase(),group=brands.get(key)||{label:product.brand,rows:[]};group.rows.push(product);brands.set(key,group)}return{type:type.label,quantity:type.rows.reduce((n,p)=>n+p.quantity,0),brands:[...brands.values()].sort((a,b)=>a.label.localeCompare(b.label)).map(brand=>{const models=new Map<string,{label:string;rows:NewStockProduct[]}>();for(const product of brand.rows){const key=product.modelNo.trim().toLowerCase(),group=models.get(key)||{label:product.modelNo,rows:[]};group.rows.push(product);models.set(key,group)}return{brand:brand.label,quantity:brand.rows.reduce((n,p)=>n+p.quantity,0),models:[...models.values()].sort((a,b)=>a.label.localeCompare(b.label)).map(model=>({model:model.label,quantity:model.rows.reduce((n,p)=>n+p.quantity,0),batches:[...model.rows].sort((a,b)=>b.purchaseDate.localeCompare(a.purchaseDate)||b.id.localeCompare(a.id,undefined,{numeric:true}))}))}})}});
}
export function soldNewStock(products:NewStockProduct[],sales:Sale[],month:string):NewStockProduct[]{
 const totals=new Map<string,{quantity:number;serials:Set<string>}>();
 for(const sale of sales){if(month&&sale.date?.slice(0,7)!==month)continue;
  const lines=sale.lineItems?.length?sale.lineItems:sale.newProductId?[{newProductId:sale.newProductId,quantity:sale.quantity,serialNumbers:sale.serialNumbers}]:[];
  for(const line of lines){const total=totals.get(line.newProductId)||{quantity:0,serials:new Set<string>()};total.quantity+=line.quantity;line.serialNumbers.forEach(sn=>total.serials.add(sn));totals.set(line.newProductId,total);}
 }
 return products.flatMap(product=>{const total=totals.get(product.id);return total?[{...product,quantity:total.quantity,serials:[...total.serials].map(sn=>({id:sn,productId:product.id,serialNumber:sn,sold:true}))}]:[]});
}
export function NewStockInventory({products,sales,isAdmin,onAdd,onDelete}:{products:NewStockProduct[];sales:Sale[];isAdmin:boolean;onAdd:()=>void;onDelete:(id:string)=>void}){
 const[query,setQuery]=useState(''),[mode,setMode]=useState('active'),[month,setMonth]=useState(todayISO().slice(0,7)),needle=query.trim().toLowerCase(),sold=mode==='sold';
 const source=sold?soldNewStock(products,sales,month):products.filter(p=>p.quantity>0).map(p=>({...p,serials:p.serials.filter(s=>!s.sold)}));
 const rows=source.filter(p=>`${p.id} ${p.accessoryType} ${p.brand} ${p.modelNo} ${p.sellerName||''} ${p.serials.map(s=>s.serialNumber).join(' ')}`.toLowerCase().includes(needle)),tree=groupNewStock(rows),action=isAdmin&&!sold;
 const stockValue=products.reduce((sum,p)=>sum+p.quantity*p.purchasePrice,0);
 const heads=['Brand','Model No.',sold?'Units Sold':'Units Available','Serial Nos.','Purchase / Unit','Seller',...(action?['Action']:[])];
 return <><div className="stockViewToolbar"><div className="tabs"><button className={`tab ${!sold?'active':''}`} onClick={()=>setMode('active')}>Existing In Stock</button><button className={`tab ${sold?'active':''}`} onClick={()=>setMode('sold')}>Sold Stock</button></div>{sold&&<StockMonthFilter value={month} onChange={setMonth} dates={sales.filter(s=>s.stockSource==='new'||s.newProductId||s.lineItems?.length).map(s=>s.date)}/>}</div><div className="sectionHead"><h3>New Stock <small>{source.reduce((n,p)=>n+p.quantity,0)} units {sold?'sold':'available'} · Available stock value {inr(stockValue)}</small></h3><button className="button" onClick={onAdd}>+ Add New Item</button></div><div className="inventorySearch"><div className="field"><label htmlFor="inventory-search">Find new stock</label><input id="inventory-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search item type, brand, model, stock ID, seller or serial number…"/></div><small>{rows.length} batches</small></div>
 <div className="tableWrap"><table className="stockAlignedTable"><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead>{tree.map(type=><tbody key={type.type} aria-label={type.type}><tr className="stockCategoryRow"><th colSpan={heads.length} scope="rowgroup">{type.type}<span>{type.quantity} units · {type.brands.length} brands</span></th></tr>{type.brands.flatMap(brand=>brand.models.map(model=>{const product=groupProducts(model.batches)[0];return <tr key={product.id}><td><b>{brand.brand}</b></td><td><b>{model.model}</b></td><td><span className={`pill ${sold?'gray':'green'}`}>{product.quantity} units</span></td><td className="stockVisibleSerials">{product.serials.length?product.serials.map(serial=>serial.serialNumber).join(', '):<span className="muted">—</span>}</td><td>{purchaseRange(product)}</td><td>{product.sellerName||'—'}</td>{action&&<td className="stockRowActions"><DeleteProductBatch product={product} onDelete={onDelete}/></td>}</tr>}))}</tbody>)}</table>{!tree.length&&<div className="empty">No matching stock found.</div>}</div></>;
}

function DeleteProductBatch({product,onDelete}:{product:ProductGroup;onDelete:(id:string)=>void}){
 const [batchId,setBatchId]=useState('');
 const removable=product.batches.filter(p=>p.quantity===p.initialQuantity&&!p.serials.some(s=>s.sold));
 if(!removable.length)return <span className="muted">—</span>;
 if(product.batches.length===1)return <button className="button danger small" onClick={()=>onDelete(removable[0].id)}>Delete</button>;
 return <details className="stockBatchActions"><summary>Delete</summary><label>Purchase batch<select aria-label={`Purchase batch to delete for ${product.brand} ${product.modelNo}`} value={batchId} onChange={e=>setBatchId(e.target.value)}><option value="">Select batch</option>{removable.map(p=><option key={p.id} value={p.id}>{p.purchaseDate} · {p.sellerName||'—'} · {inr(p.purchasePrice)} · {p.quantity} units</option>)}</select></label><button className="button danger small" disabled={!removable.some(p=>p.id===batchId)} onClick={()=>onDelete(batchId)}>Delete batch</button></details>;
}
