'use client';
import {useRef,useState} from 'react';
import {inr,todayISO} from '@/lib/ezr-utils';
import type {Bank,NewStockProduct,Seller} from '@/types/ezr';
import {SearchPicker} from './SearchPicker';
import {ContactPicker} from './ContactPicker';
export function NewStockForm({accessoryTypes,sellers,banks,existing,onSave}:{accessoryTypes:string[];sellers:Seller[];banks:Bank[];existing:NewStockProduct[];onSave:(fd:FormData)=>Promise<void>}){
 const[paymentMode,setPaymentMode]=useState('Cash'),[type,setType]=useState(''),[brand,setBrand]=useState(''),[model,setModel]=useState(''),[quantity,setQuantity]=useState('1'),[price,setPrice]=useState(''),[serialMode,setSerialMode]=useState(''),[serialText,setSerialText]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);const pending=useRef(false);
 const[paid,setPaid]=useState<string|null>(null);
 const total=Math.round(Number(price||0)*100)*Number(quantity||0)/100,amountPaid=paid??String(total),due=Math.round((total-Number(amountPaid||0))*100)/100;
 const serials=serialText.split(/[\n,]+/).map(s=>s.trim()).filter(Boolean);
 return <form className="newStockEntry" onSubmit={async e=>{e.preventDefault();if(pending.current)return;const fd=new FormData(e.currentTarget);if(!fd.get('accessoryType')||!fd.get('seller')||(paymentMode==='Online'&&!fd.get('bank'))){setError('Select a matching item type, seller and payment account.');return}if(serialMode==='yes'&&(serials.length!==Number(quantity)||new Set(serials.map(s=>s.toLowerCase())).size!==serials.length)){setError('Enter one unique serial number for every unit.');return}setError('');pending.current=true;setSaving(true);try{await onSave(fd)}finally{pending.current=false;setSaving(false)}}}>
 <fieldset className="saleFields" disabled={saving}>
 <div className="entryIntro"><b>Receive new stock</b><span>Find a previous item to fill its details, or enter a new item below.</span></div>
 <SearchPicker label="Previous item (optional)" options={existing.map(p=>({id:p.id,label:`${p.accessoryType} · ${p.brand} ${p.modelNo}`,detail:`${p.id} · Purchase ${inr(p.purchasePrice)}`}))} onChange={id=>{const p=existing.find(x=>x.id===id);if(p){setType(p.accessoryType);setBrand(p.brand);setModel(p.modelNo);setSerialMode(p.serialRequired?'yes':'');setSerialText('')}}}/>
 <div className="grid2 entryBlock">
 <SearchPicker label="Item type" name="accessoryType" required value={type} onChange={setType} options={accessoryTypes.map(x=>({id:x,label:x}))}/>
 <div className="field"><label htmlFor="new-brand">Brand</label><input id="new-brand" name="brand" value={brand} onChange={e=>setBrand(e.target.value)} list="stock-brands" required autoComplete="off"/><datalist id="stock-brands">{[...new Set(existing.map(p=>p.brand))].map(x=><option key={x} value={x}/>)}</datalist></div>
 <div className="field"><label htmlFor="new-model">Model No.</label><input id="new-model" name="modelNo" value={model} onChange={e=>setModel(e.target.value)} list="stock-models" required autoComplete="off"/><datalist id="stock-models">{[...new Set(existing.filter(p=>!brand||p.brand===brand).map(p=>p.modelNo))].map(x=><option key={x} value={x}/>)}</datalist></div>
 <div className="field"><label htmlFor="new-quantity">Quantity</label><input id="new-quantity" name="quantity" type="number" min="1" step="1" required value={quantity} onChange={e=>setQuantity(e.target.value)}/></div>
 <div className="field"><label htmlFor="new-price">Purchase Price / Unit (₹)</label><input id="new-price" name="price" type="number" min="0" step="0.01" required value={price} onChange={e=>setPrice(e.target.value)}/></div>
 <div className="field"><label htmlFor="new-date">Purchase Date</label><input id="new-date" name="date" type="date" max={todayISO()} defaultValue={todayISO()} required/></div>
 </div>
 <div className="serialEntry"><b>Does this item have serial numbers?</b><div className="choiceRow">{[['yes','Yes — enter every serial'],['no','No serial numbers']].map(([v,l])=><label key={v}><input type="radio" name="serialRequired" value={v} required checked={serialMode===v} onChange={()=>{setSerialMode(v);setSerialText('')}}/>{l}</label>)}</div>
 {serialMode==='yes'&&<div className="field"><label htmlFor="new-serials">Serial numbers · {serials.length} / {quantity||0} entered</label><textarea id="new-serials" name="serials" required rows={4} value={serialText} onChange={e=>setSerialText(e.target.value)} placeholder="Scan or enter one serial per line. Commas also separate serials."/><small>Every unit needs its own unique serial number.</small></div>}</div>
 <div className="grid2 entryBlock"><ContactPicker kind="seller" name="seller" label="Seller" contacts={sellers}/><div className="field"><label>Payment Mode</label><div className="choiceRow">{['Cash','Online'].map(m=><label key={m}><input type="radio" name="mode" value={m} checked={paymentMode===m} onChange={()=>setPaymentMode(m)}/>{m}</label>)}</div></div>{paymentMode==='Online'&&<SearchPicker name="bank" label="Bank account" required options={banks.map(b=>({id:b.id,label:b.name}))}/>}</div>
 <div className="grid2 entryBlock"><div className="field"><label htmlFor="purchase-paid">Amount Paid (₹)</label><input id="purchase-paid" name="paid" type="number" min="0" max={Number.isFinite(total)?total:0} step="0.01" required value={amountPaid} onChange={e=>setPaid(e.target.value)}/><small>Enter 0 for a fully unpaid purchase.</small></div><div className="saleSummary"><div>Purchase total: <b>{inr(total)}</b></div><div>Seller due: <b>{inr(Math.max(0,due))}</b></div><small>The unpaid balance is added to Seller Dues automatically.</small></div></div>
 {error&&<p className="error" role="alert">{error}</p>}
 </fieldset><div className="modalActions"><button className="button" disabled={saving}>{saving?'Saving…':'Add New Stock'}</button></div></form>;
}
export type NewStockTree={type:string;quantity:number;brands:Array<{brand:string;quantity:number;models:Array<{model:string;quantity:number;batches:NewStockProduct[]}>}>};
export function groupNewStock(products:NewStockProduct[]):NewStockTree[]{
 const types=new Map<string,{label:string;rows:NewStockProduct[]}>();for(const product of products){const key=product.accessoryType.trim().toLowerCase(),group=types.get(key)||{label:product.accessoryType,rows:[]};group.rows.push(product);types.set(key,group)}
 return [...types.values()].sort((a,b)=>a.label.localeCompare(b.label)).map(type=>{const brands=new Map<string,{label:string;rows:NewStockProduct[]}>();for(const product of type.rows){const key=product.brand.trim().toLowerCase(),group=brands.get(key)||{label:product.brand,rows:[]};group.rows.push(product);brands.set(key,group)}return{type:type.label,quantity:type.rows.reduce((n,p)=>n+p.quantity,0),brands:[...brands.values()].sort((a,b)=>a.label.localeCompare(b.label)).map(brand=>{const models=new Map<string,{label:string;rows:NewStockProduct[]}>();for(const product of brand.rows){const key=product.modelNo.trim().toLowerCase(),group=models.get(key)||{label:product.modelNo,rows:[]};group.rows.push(product);models.set(key,group)}return{brand:brand.label,quantity:brand.rows.reduce((n,p)=>n+p.quantity,0),models:[...models.values()].sort((a,b)=>a.label.localeCompare(b.label)).map(model=>({model:model.label,quantity:model.rows.reduce((n,p)=>n+p.quantity,0),batches:[...model.rows].sort((a,b)=>b.purchaseDate.localeCompare(a.purchaseDate)||b.id.localeCompare(a.id,undefined,{numeric:true}))}))}})}});
}
export function NewStockInventory({products,isAdmin,onAdd,onDelete}:{products:NewStockProduct[];isAdmin:boolean;onAdd:()=>void;onDelete:(id:string)=>void}){
 const[query,setQuery]=useState(''),[available,setAvailable]=useState(false),needle=query.trim().toLowerCase();
 const rows=products.filter(p=>(!available||p.quantity>0)&&`${p.id} ${p.accessoryType} ${p.brand} ${p.modelNo} ${p.sellerName||''} ${p.serials.map(s=>s.serialNumber).join(' ')}`.toLowerCase().includes(needle)),tree=groupNewStock(rows);
 return <><div className="sectionHead"><h3>New Stock <small>{products.reduce((n,p)=>n+p.quantity,0)} units available</small></h3><button className="button" onClick={onAdd}>+ Add New Item</button></div><div className="inventorySearch"><div className="field"><label htmlFor="inventory-search">Find new stock</label><input id="inventory-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search item type, brand, model, stock ID, seller or serial number…"/></div><label><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)}/> In stock only</label><small>{rows.length} batches</small></div>
 <div className="stockHierarchy">{tree.map(type=><details className="stockType" key={type.type} open={needle?true:undefined}><summary><b>{type.type}</b><span>{type.quantity} units · {type.brands.length} brands</span></summary><div className="stockTypeBody">{type.brands.map(brand=><details className="stockBrand" key={brand.brand} open={needle?true:undefined}><summary><b>{brand.brand}</b><span>{brand.quantity} units · {brand.models.length} models</span></summary><div className="stockBrandBody">{brand.models.map(model=><details className="stockModel" key={model.model} open={needle?true:undefined}><summary><b>{model.model}</b><span>{model.quantity} available · {model.batches.length} {model.batches.length===1?'batch':'batches'}</span></summary><div className="tableWrap"><table><thead><tr>{['Stock ID','Available','Serial tracking','Purchase / Unit','Seller',...(isAdmin?['Action']:[])].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{model.batches.map(product=><tr key={product.id}><td className="mono">{product.id}</td><td><span className={`pill ${product.quantity?'green':'gray'}`}>{product.quantity} units</span></td><td>{product.serialRequired?'Required':'Not required'}{product.serials.length>0&&<details><summary>{product.serials.filter(serial=>!serial.sold).length} available serials</summary><div className="serialList">{product.serials.map(serial=><div key={serial.id}>{serial.serialNumber}{serial.sold?' · Sold':''}</div>)}</div></details>}</td><td>{inr(product.purchasePrice)}</td><td>{product.sellerName||'—'}</td>{isAdmin&&<td><button className="button danger small" onClick={()=>onDelete(product.id)}>Delete</button></td>}</tr>)}</tbody></table></div></details>)}</div></details>)}</div></details>)}{!tree.length&&<div className="empty">No matching stock found.</div>}</div></>;
}
