-- EZR incremental migration: WhatsApp invoice delivery audit.
-- Safe to run after 20260901_invoice_new_stock.sql.

create table if not exists public.invoice_whatsapp_deliveries (
  id bigint generated by default as identity primary key,
  sale_id text not null references public.sales(id) on delete cascade,
  customer_id text references public.customers(id),
  phone text not null default '',
  status text not null default 'pending' check (status in ('pending','sent','failed')),
  whatsapp_message_id text,
  whatsapp_media_id text,
  error_message text not null default '',
  sent_at timestamptz,
  created_by uuid references public.profiles(id),
  created_by_name text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_invoice_whatsapp_sale on public.invoice_whatsapp_deliveries(sale_id, created_at desc);
create index if not exists idx_invoice_whatsapp_status on public.invoice_whatsapp_deliveries(status, created_at desc);

alter table public.invoice_whatsapp_deliveries enable row level security;

drop policy if exists "whatsapp delivery select authenticated" on public.invoice_whatsapp_deliveries;
create policy "whatsapp delivery select authenticated"
on public.invoice_whatsapp_deliveries for select to authenticated using (true);

drop policy if exists "whatsapp delivery insert authenticated" on public.invoice_whatsapp_deliveries;
create policy "whatsapp delivery insert authenticated"
on public.invoice_whatsapp_deliveries for insert to authenticated with check (created_by = auth.uid());

drop policy if exists "whatsapp delivery update own" on public.invoice_whatsapp_deliveries;
create policy "whatsapp delivery update own"
on public.invoice_whatsapp_deliveries for update to authenticated
using (created_by = auth.uid() or public.is_admin())
with check (created_by = auth.uid() or public.is_admin());

drop policy if exists "whatsapp delivery delete admin" on public.invoice_whatsapp_deliveries;
create policy "whatsapp delivery delete admin"
on public.invoice_whatsapp_deliveries for delete to authenticated using (public.is_admin());

grant select, insert, update, delete on public.invoice_whatsapp_deliveries to authenticated;
grant usage, select on sequence public.invoice_whatsapp_deliveries_id_seq to authenticated;
