-- EZR incremental migration: printable invoices + quantity-based new item stock.
-- Run once in Supabase SQL Editor. Existing stock/sales/purchases data is preserved.

create sequence if not exists public.new_stock_seq start 1;

create table if not exists public.new_stock_products (
  id text primary key,
  accessory_type text not null,
  brand text not null,
  model_no text not null,
  quantity integer not null default 0 check (quantity >= 0),
  initial_quantity integer not null default 0 check (initial_quantity >= 0),
  purchase_price numeric(14,2) not null default 0 check (purchase_price >= 0),
  purchase_date date not null,
  seller_id text,
  seller_name text not null default '',
  payment_mode text not null default 'Cash',
  bank_id text,
  created_by uuid references public.profiles(id),
  created_by_name text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.new_stock_serials (
  id bigint generated by default as identity primary key,
  product_id text not null references public.new_stock_products(id) on delete cascade,
  serial_number text not null,
  sold boolean not null default false,
  sale_id text,
  created_at timestamptz not null default now(),
  unique(serial_number)
);

alter table public.sales add column if not exists stock_source text not null default 'legacy';
alter table public.sales add column if not exists new_product_id text;
alter table public.sales add column if not exists quantity integer not null default 1;
alter table public.sales add column if not exists unit_price numeric(14,2);
alter table public.sales add column if not exists serial_numbers text[] not null default '{}';

alter table public.new_stock_products enable row level security;
alter table public.new_stock_serials enable row level security;

drop policy if exists "new stock select authenticated" on public.new_stock_products;
create policy "new stock select authenticated" on public.new_stock_products for select to authenticated using (true);
drop policy if exists "new stock insert authenticated" on public.new_stock_products;
create policy "new stock insert authenticated" on public.new_stock_products for insert to authenticated with check (true);
drop policy if exists "new stock update authenticated" on public.new_stock_products;
create policy "new stock update authenticated" on public.new_stock_products for update to authenticated using (true) with check (true);
drop policy if exists "new stock delete admin" on public.new_stock_products;
create policy "new stock delete admin" on public.new_stock_products for delete to authenticated using (public.is_admin());

drop policy if exists "new serial select authenticated" on public.new_stock_serials;
create policy "new serial select authenticated" on public.new_stock_serials for select to authenticated using (true);
drop policy if exists "new serial insert authenticated" on public.new_stock_serials;
create policy "new serial insert authenticated" on public.new_stock_serials for insert to authenticated with check (true);
drop policy if exists "new serial update authenticated" on public.new_stock_serials;
create policy "new serial update authenticated" on public.new_stock_serials for update to authenticated using (true) with check (true);
drop policy if exists "new serial delete admin" on public.new_stock_serials;
create policy "new serial delete admin" on public.new_stock_serials for delete to authenticated using (public.is_admin());

create index if not exists idx_new_stock_type_brand_model on public.new_stock_products(accessory_type, brand, model_no);
create index if not exists idx_new_stock_serial_product on public.new_stock_serials(product_id);
create index if not exists idx_sales_new_product on public.sales(new_product_id);
